version: '3.4'

services:
  telecomanalysis:
    image: telecomanalysis
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app:app --host 0.0.0.0 --port 8501"]
    ports:
      - 8501:8501
      - 5678:5678
